services:
  - type: web
    name: comptaorion
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && NODE_ENV=production node src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: comptaorion-db
          property: connectionString

databases:
  - name: comptaorion-db
    plan: free
    databaseName: comptaorion
    user: comptaorion_user
